import { BaseAgent } from "./BaseAgent.js";
import { titleFromName } from "../utils/slug.js";

function briefSummary(brief) {
  return String(brief || "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join(" ");
}

function offlineContent(input) {
  const title = titleFromName(input.name, "Infinity Vue Site");
  const summary = briefSummary(input.brief) || "A focused Vue site generated from a brief.";

  return {
    voice: "confident, practical, and specific",
    seo: {
      title: `${title} - Vue website generated by multi-agent workflow`,
      description: summary.slice(0, 150),
      keywords: [title, "Vue", "Vite", "multi-agent", "website generator"]
    },
    hero: {
      eyebrow: "Vue website agent demo",
      headline: title,
      lead: `${summary} The page keeps the actual experience on the first screen and stays easy to extend.`,
      primaryCta: "开始合作",
      secondaryCta: "查看能力"
    },
    metrics: [
      { value: "7", label: "Agents" },
      { value: "Vue 3", label: "Stack" },
      { value: "Ready", label: "for iteration", wide: true }
    ],
    sections: [
      {
        id: "work",
        eyebrow: "Capabilities",
        heading: "把模糊需求变成可运行页面",
        lead: "Planner, Designer, Content, and Vue Coder cooperate to turn a brief into a working front end.",
        items: [
          {
            tag: "01",
            title: "结构规划",
            description: "先定义目标、受众、页面顺序和验收标准。"
          },
          {
            tag: "02",
            title: "视觉系统",
            description: "输出色彩、版式、间距和响应式规则。"
          },
          {
            tag: "03",
            title: "内容策略",
            description: "把 brief 变成更贴近用户语言的首屏文案、CTA 和 section copy。"
          }
        ]
      },
      {
        id: "process",
        eyebrow: "Workflow",
        heading: "协作流程可追踪，也可替换",
        lead: "Each agent contributes a distinct artifact, so the pipeline is easy to inspect or replace.",
        steps: [
          { title: "Plan", text: "理解需求并拆分页面模块。" },
          { title: "Design", text: "建立界面语言和交互原则。" },
          { title: "Content", text: "打磨文案、CTA 和 SEO 信息。" },
          { title: "Build", text: "生成 Vue 文件和项目配置。" },
          { title: "Review", text: "审查质量并写入当前工作区。" }
        ]
      }
    ],
    closing: {
      eyebrow: "Next step",
      heading: "继续用 brief 驱动迭代",
      copy: "修改需求、技能或模型配置后重新运行 CLI，就能生成新的 Vue 版本。",
      email: "hello@example.com",
      cta: "联系我们"
    }
  };
}

export class ContentAgent extends BaseAgent {
  async run(input, context) {
    this.emit(context, "构建内容策略、首屏文案和 SEO 结构");

    if (context.config.offline) {
      return offlineContent(input);
    }

    const skills = this.skillRegistry.promptBlock(
      this.selectedSkills(context, ["content-strategy", "vue-data-driven-pages"])
    );

    return this.llm.chatJson({
      agentName: this.name,
      system: `You are ContentAgent. Turn a website brief into structured content for a Vue site.
Return only JSON with this shape:
{
  "voice": "brand voice",
  "seo": {
    "title": "page title",
    "description": "meta description",
    "keywords": ["keyword"]
  },
  "hero": {
    "eyebrow": "small label",
    "headline": "hero headline",
    "lead": "supporting copy",
    "primaryCta": "primary CTA",
    "secondaryCta": "secondary CTA"
  },
  "metrics": [{ "value": "metric", "label": "caption" }],
  "sections": [
    {
      "id": "work",
      "eyebrow": "section label",
      "heading": "section heading",
      "lead": "section lead",
      "items": [{ "tag": "01", "title": "item title", "description": "item description" }],
      "steps": [{ "title": "step title", "text": "step text" }]
    }
  ],
  "closing": {
    "eyebrow": "label",
    "heading": "closing heading",
    "copy": "closing copy",
    "email": "contact email",
    "cta": "cta text"
  }
}`,
      user: JSON.stringify(
        {
          brief: input.brief,
          projectName: input.name,
          plan: input.plan,
          design: input.design,
          skills
        },
        null,
        2
      )
    });
  }
}
