import { BaseAgent } from "./BaseAgent.js";
import { stableStringify } from "../utils/json.js";
import { slugify, titleFromName } from "../utils/slug.js";

function escapeHtml(input) {
  return String(input || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function normalizeFiles(result) {
  const files = result?.files;
  if (!files || typeof files !== "object" || Array.isArray(files)) {
    throw new Error("VueCoderAgent response must include a files object.");
  }

  return {
    files: Object.fromEntries(
      Object.entries(files).map(([filePath, content]) => [filePath, String(content)])
    ),
    implementationNotes: Array.isArray(result.implementationNotes)
      ? result.implementationNotes
      : []
  };
}

function offlineFiles({ name, brief, content }) {
  const rawTitle = titleFromName(name, "Infinity Vue Site");
  const rawBrief = String(brief || "").slice(0, 260);
  const contentTitle = content?.hero?.headline || rawTitle;
  const rawSiteTitle =
    content?.seo?.title || `${contentTitle} - Vue website generated by multi-agent workflow`;
  const htmlSiteTitle = escapeHtml(rawSiteTitle);
  const rawSiteDescription =
    content?.seo?.description || rawBrief || "A focused Vue site generated from a brief.";
  const htmlSiteDescription = escapeHtml(rawSiteDescription);
  const rawSiteKeywords = Array.isArray(content?.seo?.keywords) && content.seo.keywords.length > 0
    ? content.seo.keywords
    : [rawTitle, "Vue", "Vite", "multi-agent", "website generator"];
  const rawHeroLead =
    content?.hero?.lead ||
    (rawBrief
      ? `${rawBrief} The page keeps the actual experience on the first screen and stays easy to extend.`
      : "A focused Vue site generated from a brief. The page keeps the actual experience on the first screen and stays easy to extend.");
  const heroEyebrow = content?.hero?.eyebrow || "Vue website agent demo";
  const primaryCta = content?.hero?.primaryCta || "开始合作";
  const secondaryCta = content?.hero?.secondaryCta || "查看能力";
  const metrics = Array.isArray(content?.metrics) && content.metrics.length > 0
    ? content.metrics
    : [
        { value: "7", label: "Agents" },
        { value: "Vue 3", label: "Stack" },
        { value: "Ready", label: "for iteration", wide: true }
      ];
  const sections = Array.isArray(content?.sections) && content.sections.length > 0
    ? content.sections
    : [
        {
          id: "work",
          eyebrow: "Capabilities",
          heading: "把模糊需求变成可运行页面",
          lead: "Planner, Designer, Content, and Vue Coder cooperate to turn a brief into a working front end.",
          items: [
            { tag: "01", title: "结构规划", description: "先定义目标、受众、页面顺序和验收标准。" },
            { tag: "02", title: "视觉系统", description: "输出色彩、版式、间距和响应式规则。" },
            { tag: "03", title: "内容策略", description: "把 brief 变成更贴近用户语言的首屏文案、CTA 和 section copy。" }
          ]
        },
        {
          id: "process",
          eyebrow: "Workflow",
          heading: "协作流程可追踪，也可替换",
          lead: "Each agent contributes a distinct artifact, so the pipeline is easy to inspect or replace.",
          steps: [
            { title: "Plan", text: "理解需求并拆分页面模块。" },
            { title: "Design", text: "建立界面语言和交互原则。" },
            { title: "Content", text: "打磨文案、CTA 和 SEO 信息。" },
            { title: "Build", text: "生成 Vue 文件和项目配置。" },
            { title: "Review", text: "审查质量并写入当前工作区。" }
          ]
        }
      ];
  const closing = content?.closing || {
    eyebrow: "Next step",
    heading: "继续用 brief 驱动迭代",
    copy: "修改需求、技能或模型配置后重新运行 CLI，就能生成新的 Vue 版本。",
    email: "hello@example.com",
    cta: "联系我们"
  };

  return {
    "package.json": stableStringify({
      name: slugify(name, "vue-site"),
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "vite --host 0.0.0.0",
        build: "vite build",
        preview: "vite preview --host 0.0.0.0"
      },
      dependencies: {
        vue: "^3.0.0"
      },
      devDependencies: {
        "@vitejs/plugin-vue": "^5.0.0",
        vite: "^5.0.0"
      }
    }),
    "index.html": `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${htmlSiteDescription}" />
    <title>${htmlSiteTitle}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`,
    "vite.config.js": `import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

export default defineConfig({
  plugins: [vue()]
});
`,
    "src/main.js": `import { createApp } from "vue";
import App from "./App.vue";
import "./styles.css";

createApp(App).mount("#app");
`,
    "src/data/site.js": `export const site = {
  title: ${JSON.stringify(rawTitle)},
  nav: [
    { label: "作品", href: "#work" },
    { label: "流程", href: "#process" },
    { label: "联系", href: "#contact" }
  ],
  hero: {
    eyebrow: ${JSON.stringify(heroEyebrow)},
    headline: ${JSON.stringify(contentTitle)},
    lead: ${JSON.stringify(rawHeroLead)},
    primaryCta: ${JSON.stringify(primaryCta)},
    secondaryCta: ${JSON.stringify(secondaryCta)}
  },
  seo: {
    title: ${JSON.stringify(rawSiteTitle)},
    description: ${JSON.stringify(rawSiteDescription)},
    keywords: ${JSON.stringify(rawSiteKeywords, null, 2)}
  },
  metrics: ${JSON.stringify(metrics, null, 2)},
  sections: ${JSON.stringify(sections, null, 2)},
  closing: ${JSON.stringify(closing, null, 2)}
};
`,
    "src/App.vue": `<script setup>
import { site } from "./data/site.js";
</script>

<template>
  <main class="site-shell">
    <nav class="topbar" aria-label="Primary navigation">
      <a class="brand" href="#top">{{ site.title }}</a>
      <div class="nav-links">
        <a v-for="item in site.nav" :key="item.href" :href="item.href">{{ item.label }}</a>
      </div>
    </nav>

    <section id="top" class="hero section-band">
      <div class="hero-copy">
        <p class="eyebrow">{{ site.hero.eyebrow }}</p>
        <h1>{{ site.hero.headline }}</h1>
        <p class="lead">{{ site.hero.lead }}</p>
        <div class="actions">
          <a class="button primary" href="#contact">{{ site.hero.primaryCta }}</a>
          <a class="button secondary" href="#work">{{ site.hero.secondaryCta }}</a>
        </div>
      </div>
      <div class="hero-panel" aria-label="Project snapshot">
        <div v-for="metric in site.metrics" :key="metric.label" class="metric" :class="{ wide: metric.wide }">
          <strong>{{ metric.value }}</strong>
          <span>{{ metric.label }}</span>
        </div>
      </div>
    </section>

    <section
      v-for="section in site.sections"
      :id="section.id"
      :key="section.id"
      class="section-band"
      :class="section.id"
    >
      <div class="section-heading">
        <div>
          <p class="eyebrow">{{ section.eyebrow }}</p>
          <h2>{{ section.heading }}</h2>
        </div>
        <p class="section-lead">{{ section.lead }}</p>
      </div>

      <div v-if="section.items" class="card-grid">
        <article v-for="item in section.items" :key="item.title" class="feature-card">
          <span>{{ item.tag || item.title }}</span>
          <h3>{{ item.title }}</h3>
          <p>{{ item.description }}</p>
        </article>
      </div>

      <ol v-else class="steps">
        <li v-for="step in section.steps" :key="step.title">
          <strong>{{ step.title }}</strong>
          <span>{{ step.text }}</span>
        </li>
      </ol>
    </section>

    <section id="contact" class="section-band contact">
      <div>
        <p class="eyebrow">{{ site.closing.eyebrow }}</p>
        <h2>{{ site.closing.heading }}</h2>
        <p>{{ site.closing.copy }}</p>
      </div>
      <a class="button primary" :href="'mailto:' + site.closing.email">{{ site.closing.email }}</a>
    </section>
  </main>
</template>
`,
    "src/styles.css": `:root {
  color: #151719;
  background: #f7f5ef;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-synthesis: none;
  text-rendering: optimizeLegibility;
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  min-width: 320px;
}

a {
  color: inherit;
  text-decoration: none;
}

.site-shell {
  min-height: 100vh;
}

.topbar {
  align-items: center;
  background: rgba(247, 245, 239, 0.92);
  border-bottom: 1px solid rgba(21, 23, 25, 0.08);
  display: flex;
  gap: 24px;
  justify-content: space-between;
  left: 0;
  padding: 18px clamp(18px, 4vw, 56px);
  position: sticky;
  right: 0;
  top: 0;
  z-index: 10;
}

.brand {
  font-weight: 800;
}

.nav-links {
  display: flex;
  gap: clamp(12px, 3vw, 28px);
  font-size: 14px;
}

.section-band {
  padding: clamp(56px, 8vw, 96px) clamp(18px, 4vw, 56px);
}

.hero {
  align-items: stretch;
  display: grid;
  gap: clamp(28px, 5vw, 64px);
  grid-template-columns: minmax(0, 1.1fr) minmax(280px, 0.9fr);
  min-height: calc(100vh - 65px);
}

.hero-copy {
  align-self: center;
  max-width: 760px;
}

.eyebrow {
  color: #0f766e;
  font-size: 13px;
  font-weight: 800;
  letter-spacing: 0;
  margin: 0 0 14px;
  text-transform: uppercase;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  font-size: clamp(48px, 8vw, 92px);
  letter-spacing: 0;
  line-height: 0.94;
  margin-bottom: 24px;
  max-width: 900px;
}

h2 {
  font-size: clamp(32px, 5vw, 56px);
  letter-spacing: 0;
  line-height: 1;
  margin-bottom: 18px;
}

h3 {
  font-size: 21px;
  margin-bottom: 12px;
}

.lead {
  color: #49515c;
  font-size: clamp(18px, 2vw, 22px);
  line-height: 1.65;
  max-width: 720px;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 32px;
}

.button {
  align-items: center;
  border-radius: 8px;
  display: inline-flex;
  font-weight: 800;
  justify-content: center;
  min-height: 46px;
  padding: 12px 18px;
}

.button.primary {
  background: #151719;
  color: #fff;
}

.button.secondary {
  background: #fff;
  border: 1px solid rgba(21, 23, 25, 0.16);
}

.hero-panel {
  align-content: end;
  background: linear-gradient(140deg, #0f766e, #151719 54%, #7c3aed);
  border-radius: 8px;
  color: #fff;
  display: grid;
  gap: 12px;
  grid-template-columns: 1fr 1fr;
  min-height: 420px;
  padding: 18px;
}

.metric {
  background: rgba(255, 255, 255, 0.12);
  border: 1px solid rgba(255, 255, 255, 0.22);
  border-radius: 8px;
  padding: 18px;
}

.metric strong {
  display: block;
  font-size: 28px;
  margin-bottom: 8px;
}

.metric span {
  color: rgba(255, 255, 255, 0.78);
}

.metric.wide {
  grid-column: 1 / -1;
}

.work {
  background: #fff;
}

.section-heading {
  display: grid;
  gap: 24px;
  grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);
  margin-bottom: 32px;
}

.section-lead {
  color: #49515c;
  line-height: 1.7;
  margin-bottom: 0;
}

.card-grid {
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.feature-card {
  background: #f7f5ef;
  border: 1px solid rgba(21, 23, 25, 0.08);
  border-radius: 8px;
  min-height: 220px;
  padding: 24px;
}

.feature-card span {
  color: #7c3aed;
  display: inline-block;
  font-weight: 900;
  margin-bottom: 12px;
}

.feature-card p,
.contact p,
.steps span {
  color: #667085;
  line-height: 1.65;
}

.process {
  display: grid;
  gap: 40px;
  grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);
}

.steps {
  counter-reset: step;
  display: grid;
  gap: 12px;
  list-style: none;
  margin: 0;
  padding: 0;
}

.steps li {
  align-items: baseline;
  background: rgba(255, 255, 255, 0.72);
  border: 1px solid rgba(21, 23, 25, 0.08);
  border-radius: 8px;
  display: grid;
  gap: 10px;
  grid-template-columns: 120px 1fr;
  padding: 18px;
}

.contact {
  align-items: center;
  background: #151719;
  color: #fff;
  display: flex;
  gap: 28px;
  justify-content: space-between;
}

.contact p {
  color: rgba(255, 255, 255, 0.72);
  margin-bottom: 0;
  max-width: 640px;
}

.contact .eyebrow {
  color: #f59e0b;
}

.contact .button.primary {
  background: #fff;
  color: #151719;
  flex: 0 0 auto;
}

@media (max-width: 820px) {
  .topbar {
    align-items: flex-start;
    flex-direction: column;
  }

  .hero,
  .section-heading,
  .process,
  .card-grid {
    grid-template-columns: 1fr;
  }

  .hero {
    min-height: auto;
  }

  .hero-panel {
    min-height: 320px;
  }

  .steps li {
    grid-template-columns: 1fr;
  }

  .contact {
    align-items: flex-start;
    flex-direction: column;
  }
}
`,
    "README.md": `# ${rawTitle}

Generated by Infinity Vue Agent.

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`
`
  };
}

export class VueCoderAgent extends BaseAgent {
  async run(input, context) {
    this.emit(context, "生成 Vite + Vue 3 项目文件");

    if (context.config.offline) {
      return {
        files: offlineFiles({
          name: input.name,
          brief: input.brief,
          content: input.content
        }),
        implementationNotes: ["Generated by deterministic offline VueCoderAgent."]
      };
    }

    const skills = this.skillRegistry.promptBlock(
      this.selectedSkills(context, [
        "vue-website-maker",
        "design-system",
        "vue-data-driven-pages"
      ])
    );

    const result = await this.llm.chatJson({
      agentName: this.name,
      system: `You are VueCoderAgent. Generate a complete Vite + Vue 3 website project.
Return only JSON with this exact shape:
{
  "files": {
    "package.json": "file contents",
    "index.html": "file contents",
    "vite.config.js": "file contents",
    "src/main.js": "file contents",
    "src/data/site.js": "file contents",
    "src/App.vue": "file contents",
    "src/styles.css": "file contents",
    "README.md": "file contents"
  },
  "implementationNotes": ["short notes"]
}

Rules:
- Use Vue 3 single-file components and Vite.
- Do not use markdown fences around file contents.
- All file paths must be relative and must not include "..".
- The generated site must be usable as the first screen, not a marketing placeholder.
- Keep UI responsive and avoid overlapping text.
- Prefer a data-driven App.vue that imports content from src/data/site.js.
- Let src/data/site.js export title, seo, nav, hero, metrics, sections, and closing content when useful.
- If you add dependencies, include them in package.json.`,
      user: JSON.stringify(
        {
          brief: input.brief,
          projectName: input.name,
          plan: input.plan,
          design: input.design,
          content: input.content,
          skills
        },
        null,
        2
      )
    });

    return normalizeFiles(result);
  }

  async revise(input, context) {
    this.emit(context, "根据审查意见进行一次代码修订");

    if (context.config.offline) {
      return input.currentCode;
    }

    const result = await this.llm.chatJson({
      agentName: this.name,
      system: `You are VueCoderAgent. Revise the full Vue project files based on review feedback.
Return only JSON with this exact shape:
{
  "files": {},
  "implementationNotes": ["short notes"]
}`,
      user: JSON.stringify(
        {
          brief: input.brief,
          plan: input.plan,
          design: input.design,
          content: input.content,
          currentFiles: input.currentCode.files,
          review: input.review
        },
        null,
        2
      )
    });

    return normalizeFiles(result);
  }
}
